### PR TITLE
v0.2.12 manage over reticulated split

### PR DESCRIPTION
**Pull request by juniperlsimonis**
overly reticulated splits can't be plotted vertically.
introduced a cap on the length of the output, currently set to 100. i'm not sure if this is the exactly right value to use, so this may need to be updated, but it should catch the issue
also removing modal welcome function

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
oh and the predictor column check for the app now also pre-excludes any column names with . or - in them

**Comment by ddalthorp** [comment]
we'll need to make it clear somewhere what the problem is: "Why aren't my predictors showing up in the dropdown list?!" Maybe a note in the User Guide + troubleshooting doc for things like that..

**Comment by ddalthorp** [comment]
if (!is.null(try(plot(splitSum, rate))) stop(...)

**Comment by juniperlsimonis** [comment]
unfortunately, given the way the plot code is for the splits, that actually still throws an error about the figure margins (thrown by `plot.new()`) before the error is thrown by `plot.splitsFull()`, and which isn't collected by the `try` functions at that level because of the scoping of plot objects. that means it doesn't address the issue that we're trying to avoid here.

**Pull request merged**
